# -*- coding: utf-8 -*-
"""producer_tweets_finale.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIW2hyMiKWU1k5MaiNSwVoAtTmYMIpsH

Il codice esegue le seguenti operazioni:


*   Importa le librerie necessarie per la corretta esecuzione

*   Crea un producer Kafka

*   Legge un file di formato json contenente i tweets scaricati in un determinato intervallo temporale

*   I tweets contenuti nel file sono inviati dal producer precedentemente creato ad uno specifo topic, in modo tale che possano essere processati da un consumer (in questo caso il cosumer viene settato sulla piattaforma nifi)
"""

# set up

# !pip3 install git+https://github.com/dpkp/kafka-python
from kafka import KafkaProducer
import json
import time

# producer creation

producer = KafkaProducer(
    bootstrap_servers = ["kafka:9092"],
    value_serializer = lambda v: json.dumps(v).encode("UTF-8"))

# lettura file json tweets scaricati

tweets_final = json.load(open("tweets_scaricati_23_26_novembre.json"))

# tweets -> topic -> mongodb

for tweet in tweets_final:
    # print(tweet)
    producer.send(topic='tweets_nifi_consumer', value=tweet)
    # print("tweet delivered")
    # time.sleep(2)