# -*- coding: utf-8 -*-
"""creazione_struttura_documento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dROGX8xJyQw23y1ZWTGmG9ja_X1cCQV3
"""

# !pip install pymongo
# !pip install numpyencoder
# !pip install simplejson

import pandas as pd
# from pymongo import MongoClient
import json
import simplejson
import numpy
from numpyencoder import NumpyEncoder

# funzione
def costruzione_doc(year, dati_donne_indicatori_stato_anno):

  anno = year
  dati_donne_indicatori_stato_anno = dati_donne_indicatori_stato_anno

  elenco_donne = {
      "donne vincitrici" : []
  }

  indicatori = {
      "indicatori": []
  }

  document[anno] = []
  document[anno].append(elenco_donne)
  document[anno].append(indicatori)

  # inserisco i dati

  for row in dati_donne_indicatori_stato_anno.itertuples():
    donna_dati = {
             "nome": row.name,
             "img": row.img,
             "age": row.age,
             "catogory": row.category,
             "role": row.job,
             "description": row.description
             }
    indicatori_stato = {
              "gdp":row.gdp,
              "gdp_capite": row.gdp_pro_capita,
              "ratio_labour": row.ratiolabour,
              "gender_gap": row.gender_gap
          }
    elenco_donne.get("donne vincitrici").append(donna_dati)

    if indicatori.get("indicatori") == []:
      indicatori.get("indicatori").append(indicatori_stato)

csv_db= pd.read_csv('tabelle_finali_donne_indicatori_stati/tabella_finale.csv')
csv_groups= csv_db.groupby("country") # raggruppo per stato

documents = []

for stato in csv_groups: # ciclo sui vari stati

  nome_stato = stato[0] # nome dello stato considerato
  donne_indicatori_stato = stato[1] # donne vincitrici dello stato in questione + indicatori stato

  document = {
      "stato" : nome_stato
    }

  donne_indicatori_group_year = donne_indicatori_stato.groupby('anno') # raggruppo per anno le donne vincitrici dello stato in questione
  
  for donne_indicatori_year in donne_indicatori_group_year: # considero le donne del 2015, le donne del 2020 per lo stato in questione

     anno = donne_indicatori_year[0] # anno considerato
     dati_donne_indicatori_stato_anno = donne_indicatori_year[1] # donne vincitrici dello stato in questione + indicatori stato per lo specifico anno e stato
     
     if anno == 2015:
      costruzione_doc("2015", dati_donne_indicatori_stato_anno) # inserisco dati per il 2015
     if anno == 2019:
       costruzione_doc("2019", dati_donne_indicatori_stato_anno) # inserisco dati per il 20219

  documents.append(document) # passo ad analizzare un nuovo stato

print(documents)

with open('prova.json', 'w') as f:
  simplejson.dump(documents, f, ignore_nan=True)
  # json.dump(documents, f, cls=NumpyEncoder)