# -*- coding: utf-8 -*-
"""Copia di gender_gap_2015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2_P92vgbg8830dnfkgZbzgnZR6Z_fbI
"""

import requests
import pandas as pd

base_site = 'https://reports.weforum.org/global-gender-gap-report-2015/rankings/'

r = requests.get(base_site)
r.status_code

tables = pd.read_html(r.text)[0]

tables

output = tables.to_csv("dati_donne_indicatori_stati/global gender gap 2015/gender_gap_2015_original.csv", index=False)