# -*- coding: utf-8 -*-
"""Copy of find_alhpa3Code_states.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m-VvyuO_AJ1jUtsxb9rR8dag75NO5XrH
"""

url = "https://www.iban.com/country-codes"

import pandas as pd

dfs = pd.read_html(url)

table = dfs[0]

table

final = pd.DataFrame(data=table)

final.drop(['Alpha-2 code', 'Numeric'], axis=1, inplace=True)

final

exporting_to_csv = final.to_csv("alpha3code_states.csv", index=False)